### ISSUE TITLE
license

### ISSUE THREAD

**Issue by cre4ture** [motorailgun/fuse-grpc-rs#1]
Hi, I'm currently doing some research for a private project including a GRPC based filesystem.
I stumbled accross your work in this repo. I think I could make use of it.

Would you mind changing the license from GPL 3.0 to MIT?

I'm not a license expert and as its a private project it probably doesn't matter much.
I was just wondering why GPL? Most of the other rust crates are MIT or Apache 2.0 which are quite relaxed licenses such that one doesn't need to worry at all.

Kind regards

**Comment by cre4ture** [comment]
I've learned that there are some differences between the needs of my project and the implementation here. So I think I need to write some own protofiles and the corresponding implementation.

**Comment by motorailgun** [comment]
🫡

Even though this project is licensed under GPL, I don't mind if anyone read and learn from my code (I think such cases aren't covered by the license). I wish you the best luck!
